deeptruth/src/main/java/com/deeptruth/deeptruth/base/Enum/DeepfakeResult.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/deepfake/DeepfakeDetectionDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/entity/DeepfakeDetection.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/DeepfakeDetectionServiceTest.java
- deepFakeResult 컬럼 Float 에서 Enum(real/fake)로 변경
- detectedPart 필드 삭제 
- deepFakeResult 를 REAL/FAKE로 반환할 수 있도록 Enum을 만들어 설정했습니다.
- 딥페이크 탐지 모델에서 자동으로 탐지 영역이 이미지로 출력되어 json 형식의 detectedPart가 필요 없어 삭제했습니다.
- 관련 DTO와 TEST 수정했습니다
> #39
=> Refactor: DeepfakeDetection Entity 필드 수정 및 DTO, Test 수정

deeptruth/build.gradle, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/deepfake/FlaskResponseDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/config/WebClientConfig.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/UserRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/AmazonS3Service.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/UserService.java
- Deepfake Flask 서버와 연동
- 결과값으로 받은 Base64 uri를 디코딩해 S3에 저장
- 결과값을 저장한 후 DeepfakeDetectionDTO로 받아왔습니다
#40 
- 시간 관계상 TDD로 개발하지 못하였습니다. 추후 테스트 코드 개발 예정입니다.
=> Feat: Flask 서버 연동해 결과 이미지 S3 저장

deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/watermark/WatermarkDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/DeepfakeDetectionServiceTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/WatermarkServiceTest.java
- 워터마크 삽입 기록 전체 조회 기능
- 워터마크 삽입 기록 개별 조회 기능
- 워터마크 삽입 기록 삭제 기능
- WatermarkDTO를 이용해 기록 조회 가능합니다
- Watermark id를 이용해 개별 조회 및 삭제 가능합니다.
- 기능 관련 controllreTest 및 serviceTest 구현했습니다. 
> #45
=> Feat: 워터마크 삽입 기록 조회 및 삭제 기능 구현

.idea/dataSources.local.xml, .idea/modules.xml, deeptruth/build.gradle, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/login/LoginRequestDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/signup/SignupRequestDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/constants/LoginConstants.java, deeptruth/src/main/java/com/deeptruth/deeptruth/constants/SignupConstants.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/UserController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/UserService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/util/JwtUtil.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/UserControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/UserServiceTest.java
- 로그인 기능 TDD 방식 구현
- JWT 토큰 생성 및 인증 처리
- RESTful API 엔드포인트 (/api/login)
- 유효성 검사: 아이디/비밀번호 null/empty 체크
- 인증 처리: 사용자 존재 여부 및 비밀번호 일치 확인
- JWT 토큰: 로그인 성공 시 JWT 토큰 생성 반환
- API: UserController.login() 엔드포인트 구현
- 테스트: UserServiceTest, UserControllerTest 모든 케이스 통과
- 리팩토링: JWT 유틸리티 분리 및 상수 추출 
> #49 
로그인 기능 구현하면서 코드 구조 개선한 부분들 설명드리겠습니다!
**JwtUtil 클래스 분리**
- 재사용성: 추후에 다른 서비스에서도 JWT 써야 할 때 편하게 쓸 수 있도록 분리했습니다.
- 단일 책임: UserService에서 JWT까지 다 하면 복잡해져서 분리했습니다.
**Constants 패키지 분리**
- 매직 스트링 제거: 하드코딩 문자열들 상수로 빼서 관리하기 쉽게 했습니다.
- 일관성: 같은 에러 메시지 여러 곳에서 써도 실수하지 않도록 수정했습니다.
- 확장성: 나중에 메시지 수정하거나 다국어 지원할 때 편할 것 같습니다.
추가로 궁금한 점 있으시면 언제든 말씀해 주세요~
=> ETR 59 일반 로그인 기능 TDD 구현

deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/watermark/WatermarkFlaskResponseDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
Flask에서 워터마크가 삽입된 이미지를 생성하고, 해당 이미지를 Spring 서버로 전달받아 S3에 업로드하는 기능을 구현했습니다.
- Spring `POST /watermark` 컨트롤러:
- 클라이언트로부터 이미지와 메시지 수신
- Flask 서버에 `multipart/form-data`로 요청 전송
- 응답으로 받은 base64 이미지를 S3에 업로드
- 업로드된 S3 URL을 DB에 저장 (`Watermark` 엔티티)
> #44 
- Flask 워터마크 삽입 서버는 `localhost:5000` 기준으로 연동됐습니다
- 추후 배포 시 외부 도메인으로 `flaskServerUrl` 환경 변수 설정 필요합니다
=> Feat: 워터마크 삽입 이미지 Flask 연동 및 S3 업로드 기능 추가

deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/WatermarkServiceTest.java
워터마크 삽입 기록 전체 조회 시 결과가 많아지는 문제를 해결하기 위해, 15건 단위의 페이징 기능을 적용했습니다.
- `/watermark` GET API에 `Pageable` 파라미터 적용
- 기본 `page=0`, `size=15`, 정렬은 `createdAt DESC`
- 컨트롤러에서 `PageableDefault`를 사용해 기본값 설정
- 서비스 및 Repository 계층에 `Page<WatermarkDTO>` 반환 방식 도입
> #45
=> Refactor: 워터마크 전체 조회 API에 15건 단위 페이징 기능 추가

deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/DeepfakeDetectionRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java
딥페이크 탐지 기록 전체 조회 시 결과가 많아지는 문제를 해결하기 위해, 15건 단위의 페이징 기능을 적용했습니다.
- `/deepfake` GET API에 `Pageable` 파라미터 적용
- 기본 `page=0`, `size=15`, 정렬은 `createdAt DESC`
- 컨트롤러에서 `PageableDefault`를 사용해 기본값 설정
- 서비스 및 Repository 계층에 `Page<DeepfakeDetectionDTO>` 반환 방식 도입
> #34
=> Refactor: 딥페이크 전체 조회 API에 15건 단위 페이징 기능 추가

deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
- 잘못된 `Pageable` import (`java.awt.print.Pageable`) → `org.springframework.data.domain.Pageable`로 교체
- `application.yml`에서 잘못된 설정 키(`deekfake-server`, `watermark-server`)를 camelCase(`deepfakeServer`, `watermarkServer`)로 변경
- 관련 `@Value` 키도 함께 수정하여 Spring Boot 애플리케이션 부팅 오류 해결
1. `WatermarkRepository`에서 잘못 사용된 `Pageable` import 수정:
- ❌ `java.awt.print.Pageable` → ✅ `org.springframework.data.domain.Pageable`
- 해당 문제로 인해 Spring Data JPA가 query 메서드를 생성하지 못하고 `LinkageError` 및 `UnsatisfiedDependencyException` 발생함
2. `application.yml` 내 설정 키 변경:
- ❌ `flask.deekfake-server.url` → ✅ `flask.deepfakeServer.url`
- ❌ `flask.watermark-server.url` → ✅ `flask.watermarkServer.url`
- Java에서 `@Value`로 주입받는 키와 불일치로 인해 Spring 부팅 실패 발생
- 키 이름을 camelCase로 변경하여 하이픈 기반 매핑 오류 예방
3. 관련 `@Value` 어노테이션 키도 함께 수정: …
=> Fix: 잘못된 Pageable import 및 application.yml 설정 키 수정

deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/watermark/WatermarkDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/entity/Watermark.java
- 더 이상 originalFilePath가 사용되지 않아 엔티티/스키마에서 제거합니다.
- API 보호를 위해 JWT 기반 인증/인가를 추가했습니다.
1. Entity/DB
- watermark.original_file_path 컬럼 제거
- 관련 DTO 수정
2. POST /watermark API 변경
- Authorization: Bearer <token> 필요
#44 
MySQL에서 아래와 같은 작업 필요합니다! 
`ALTER TABLE watermark DROP COLUMN IF EXISTS original_file_path;
`
=> originalFilePath 필드 제거 및 JWT 인증 적용

deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DetectionNotFoundException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/ExternalServiceException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/ImageDecodingException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidDetectionResponseException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidFileException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidWatermarkResponseException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/StorageException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/UserNotFoundException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/WatermarkNotFoundException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/DeepfakeDetectionRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
- 도메인 맞춤 **커스텀 예외** 추가 및 **GlobalExceptionHandler** 도입으로 API 에러 응답 일원화
- **DeepfakeDetectionService**, **WatermarkService** 리팩터링: 서비스 계층에서 의미 있는 예외를 던지고 컨트롤러는 얇게 유지
- 스토리지/외부 연동/입력 유효성/리소스 없음 등 상황별 **HTTP 상태 코드 명확화**
- `UserNotFoundException` (404)
- `DetectionNotFoundException` (404)
- `WatermarkNotFoundException` (404)
- `InvalidFileException` (400)
- `ImageDecodingException` (400)
- `InvalidDetectionResponseException` (422)
- `InvalidWatermarkResponseException` (422)
- `StorageException` (5xx)
- `ExternalServiceException` (5xx)
> 목적: 예외 의미를 명시적으로 표현하고, GlobalExceptionHandler에서 상태 코드/응답 포맷을 일관되게 반환.
- `@RestControllerAdvice` 기반 전역 예외 처리기
- 매핑 규칙
- 404: `UserNotFoundException`, `DetectionNotFoundException`, `WatermarkNotFoundException`
- 400: `InvalidFileException`, …
=> Feat: 커스텀 예외 추가 및 GlobalExceptionHandler 구현; Refacotr: 에러 처리를 위한 deepfake & watermark service 수정

deeptruth/src/main/java/com/deeptruth/deeptruth/base/Enum/DeepfakeDetector.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/Enum/DeepfakeMode.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/deepfake/DeepfakeDetectionDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/deepfake/FlaskResponseDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/entity/DeepfakeDetection.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
- Deepfake 응답에 정밀 모드 옵션 7개를 추가했습니다. 
- DeepfakeDetection 엔티티에 탐지 모드(DetectionMode), 탐지기 종류 등 옵션 7개 필드 추가
- FlaskResponseDTO → DeepfakeDetection 변환 시 문자열 → Enum 매핑 로직 적용
- DB에는 EnumType.STRING 방식으로 저장되어 "DEFAULT", "PRECISION", "AUTO", "DLIB", "DNN" 등 명확한 값이 남도록 개선
#40
=> Fix: Deepfake 응답에 정밀모드 옵션 추가

deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseFlaskResponseDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/NoiseController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/entity/Noise.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java
> 적대적 노이즈 자동/정밀 모드 mode, level 필드 연동 및 Spring Boot 백엔드 구현 완성
- **NoiseController**: Flask API 호출 시 mode, level 파라미터 전달 로직 추가
- **NoiseFlaskResponseDTO**: mode, level 필드 추가 및 JsonProperty 매핑
- **Noise Entity**: mode(String), level(Integer) 컬럼 추가
- **NoiseService**: Flask 응답 데이터의 mode, level을 DB에 저장하도록 구현
- **NoiseDTO**: mode, level, modeDescription 필드 추가 및 변환 메서드 수정
- **파라미터 검증**: 잘못된 mode, level 값에 대한 400 에러 처리 추가
> #86
**1. 요청 (POST /api/noise):**
- `file`: MultipartFile (이미지 파일) - **필수**
- `mode`: "auto" | "precision" (기본값: "auto") - **선택**
- `level`: 1 | 2 | 3 | 4 (정밀 모드에서만 사용, 기본값: 2) - **선택**
**요청 예시:**
```
formData.append('file', 이미지파일);            // 필수
formData.append('mode', 'precision');         // 자동/정밀
formData.append('level', '3');                // 정밀 모드 시 단계
```
**2. 응답 데이터 …
=> Feat: 적대적 노이즈 자동/정밀 모드 mode, level 필드 연동 및 히스토리 API 반영

deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkDetectionService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
워터마크 삽입/탐지 기능에 WebSocket 기반 진행률 전송 기능 추가했습니다. Flask 서버에서 전송한 진행률 데이터를 Spring이 수신하고, 구독 중인 클라이언트에게 실시간 브로드캐스트합니다.
삽입과 탐지에 `@RequestParam(required = false) String taskId`로 taskId를 받아와 진행률을 프론트로 브로드 캐스트합니다. 
#44
=> Feat: 워터마크 기능에 대한 taskId 전달 플로우 추가 

deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/ArtifactNotFoundException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DataCorruptionException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DataMappingException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/FileEmptyException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidEnumValueException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidFilenameException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/S3UploadFailedException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/SimilarityThresholdExceededException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/UnauthorizedException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/UnsupportedMediaTypeException.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/AmazonS3Service.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkDetectionService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
딥페이크와 워터마크, S3 업로드와 관련된 전역 예외 처리(GlobalExceptionHandler)를 도입하여 서비스 및 컨트롤러 전반에서 발생하는 예외를 일관된 `ResponseDTO` 포맷으로 응답하도록 개선했습니다.  예외 상황별로 명확한 HTTP 상태 코드와 메시지를 내려 클라이언트 단 처리와 디버깅 편의성을 높였습니다.
- 커스텀 예외 클래스 정의 (`RuntimeException` 상속)
- `FileEmptyException`, `InvalidFilenameException`, `InvalidEnumValueException` (400)
- `UnsupportedMediaTypeException` (415)
- `DataCorruptionException`, `DataMappingException`, `SimilarityThresholdExceededException` (422)
- `S3UploadFailedException` (502)
- `UnauthorizedException` (401)
- `ArtifactNotFoundException`(404)
- 서비스 코드에서 `RuntimeException` 대신 의미 있는 커스텀 예외 사용
- AmazonS3Service, DeepfakeDetectionService, WatermarkService, WatermarkDetectionService 등 적용
- 컨트롤러에서 불필요한 try/catch 제거 → 전역 핸들러가 처리하도록 위임
#65 
- 현재는 `ResponseDTO`를 성공/실패 모두에 재사용 중인데, 필요하다면 …
=> Feat: Deepfake 및 Watermark, S3 서비스에 관련된 전역 예외 처리 도입 

deeptruth/src/main/java/com/deeptruth/deeptruth/DeeptruthApplication.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java, deeptruth/src/main/java/com/deeptruth/deeptruth/constants/LoginConstants.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/UserController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/DeepfakeDetectionRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/NoiseRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/UserRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java, deeptruth/src/main/java/com/deeptruth/deeptruth/scheduler/UserCleanupScheduler.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/UserService.java, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/scheduler/UserCleanupSchedulerTest.java
> 탈퇴 회원 자동 삭제 기능을 구현했습니다. 30일 경과한 회원을 대상으로 연관 데이터와 함께 삭제하며, 개별 오류 발생 시에도 나머지 회원 처리는 계속 진행됩니다.
**1. 예외 처리 체계 정리 및 상수 활용 개선**
- HTTP 상태코드 매핑
- UnauthorizedException(401): 로그인 실패, 인증 실패
- UnauthorizedOperationException(403): 권한 부족, 접근 제한
- UserNotFoundException(404): 요청한 사용자 ID가 존재하지 않음
- 상수 분리: LoginConstants에 공통 메시지 상수 추가
**2. 사용자 데이터 정리 스케줄러 테스트 작성**
- UserCleanupSchedulerTest 구현
- 여러 시나리오 검증 (정상 처리/예외 상황/견고성)
- 30일 경과 탈퇴 회원 자동 삭제 기능 테스트
- WatermarkControllerTest 오류로 인한 임시 주석 처리
**3. 회원 자동 삭제 스케줄러 기능 구현**
- UserCleanupScheduler 구현
- 30일 경과 탈퇴 회원 자동 삭제
- 연관 데이터 함께 삭제: 딥페이크 탐지, 워터마크, 적대적 노이즈 기록
- @SQLRestriction 우회를 위한 nativeQuery 활용
- 개별 삭제 실패 시에도 다른 회원 처리 지속
- 매일 새벽 2시 자동 실행되는 Cron 스케줄러
> #96 #98
> WatermarkControllerTest 오류로 인한 임시 주석 처리해 두었습니다.
=> Feat: 회원 데이터 자동 정리 시스템 구현

deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
createDetection param의 코드 표기법을 변경하였습니다.
프론트에서 카멜 표기법으로 받아, 스네이크 표기법으로 넘기는 것으로 변경했습니다. 
```
passThrough(mb, "taskId", taskId);
passThrough(mb, "mode", form.get("mode"));
passThrough(mb, "detector", form.get("detector"));
passThrough(mb, "useTta", form.get("use_tta"));
passThrough(mb, "useIllum", form.get("use_illum"));
passThrough(mb, "minFace", form.get("min_face"));
passThrough(mb, "sampleCount", form.get("sample_count"));
passThrough(mb, "smoothWindow", form.get("smooth_window"));
```
=> Fix: createDetection param 값 불러오기 변경

deeptruth/build.gradle, deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/WatermarkServiceTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/testsecurity/WithMockCustomUser.java, deeptruth/src/test/java/com/deeptruth/deeptruth/testsecurity/WithMockCustomUserSecurityContextFactory.java
- Watermark 서비스 및 컨트롤러 단위 테스트 작성
- 인증된 사용자 시나리오 테스트를 위한 @WithMockCustomUser 어노테이션 추가
- Flask WebClient 응답 mock 처리
- AmazonS3Service mock 업로드 검증
- UserNotFoundException, ImageDecodingException 등 예외 상황 검증
- DB 저장 및 DTO 반환 로직 테스트
- MockMvc 기반 워터마크 삽입 API 성공/실패 케이스 검증
- multipart 업로드 + 파라미터 전달 시나리오 테스트
- ResponseDTO 기본 필드(status, success, message, data) 검증
- @WithSecurityContext 기반으로 SecurityContext에 CustomUserDetails 주입
- 컨트롤러 테스트에서 인증 유저 시나리오를 간단히 표현 가능
#44 #45
=> Test: 워터마크 서비스, 컨트롤러 테스트 수정 및 WithMockCustomUser 생성

deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java, deeptruth/src/test/java/com/deeptruth/deeptruth/service/DeepfakeDetectionServiceTest.java
- 딥페이크 탐지 모듈의 서비스 단위 테스트와 컨트롤러 단위 테스트를 추가했습니다.
- Flask 연동 실패 케이스, DTO 매핑, MockMvc 기반의 API 응답 검증을 포함합니다.
- `createDetection_success`: Flask 응답 매핑, base64 업로드, bullet 계산, DB 저장 로직 정상 동작 검증
- `createDetection_flaskRequestError`: Flask 서버 연결/타임아웃 시 ExternalServiceException 발생 검증
- `getSingleResult`, `getAllResult`, `deleteResult` 정상 동작 시나리오 추가
- `POST /api/deepfake`: 멀티파트 업로드 성공 응답 검증 (taskId, result, filePath 등)
- `GET /api/deepfake/{id}`: 단건 조회 성공 응답 검증
- `GET /api/deepfake`: 페이지네이션 전체 조회 성공 응답 검증
- `DELETE /api/deepfake/{id}`: 삭제 성공 응답 검증
- `@WithMockCustomUser` 활용하여 인증 객체를 주입, 보안 필터 체인은 `addFilters=false`로 비활성화
-` JwtAuthenticationFilter`를 테스트 스코프에서 제외하여 JwtUtil 빈 의존성 문제 해결
#34 #35 
현재는 시큐리티 필터를 제외했는데, 인증/인가를 실제로 검증하는 E2E 테스트도 별도로 구성할지 의견 부탁드립니다.
=> Test: Deepfake 서비스/컨트롤러 테스트 추가

deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkDetectionService.java
현재 phash 임계값이 18로 설정되어 있어, 이미지를 조금만 크롭하거나 변형해도 유사도가 크게 떨어지는 문제가 있었습니다.  
이를 해결하기 위해 임계값을 30으로 상향 조정했습니다.
- phash 임계값 18 → 30으로 조정
- 여러 크롭/리사이즈 테스트를 통해 안정적인 결과 확인
- 
#44
=> Fix: pHash 임계값 변경

deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java, deeptruth/src/main/java/com/deeptruth/deeptruth/config/WebConfig.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/NoiseController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java
> 적대적 노이즈 기능에 사용자별 실시간 진행률 연동을 추가하고, WebSocket 통신을 위한 보안 정책을 통합 개선했습니다. 기존 ProgressController와 연동되어 개인별 진행률 전송이 가능해졌습니다.
**1. 적대적 노이즈 기능 개선 및 최적화**
- NoiseController/Service 아키텍처 고도화
- 기존 계층화 구조를 기반으로 성능 최적화
- Service Layer의 Flask API 통신 로직을 더욱 안정적으로 개선
- 에러 핸들링 및 파일 처리 로직 강화로 견고성 향상
- 팀 협업을 위한 코드 일관성 및 가독성 향상
**2. 사용자별 실시간 진행률 연동 기능 추가**
- 기존 ProgressController와 연동
- NoiseService → Flask 호출 시 loginId 전달로 사용자 식별
- Flask → ProgressController → WebSocket을 통한 개인별 진행률 전송
- convertAndSendToUser() 활용하여 보안성 강화 (개인별 타겟팅)
- DeepfakeService, WatermarkService와 동일한 패턴으로 일관성 유지
**3. WebSocket 실시간 진행률을 위한 보안 및 CORS 설정 개선**
- SecurityConfig 보안 정책 통합 개선
- WebSocket 엔드포인트(/ws/**, /progress/**) 접근 허용
- 인증/비인증 API 경로 명확한 분리로 보안 체계 정립
- WebConfig CORS 정책 개선
- 도메인 하드코딩 → 환경변수 방식으로 배포 친화적 변경
- 성능 최적화 및 운영 환경별 …
=> Feat: 적대적 노이즈 실시간 진행률 연동 및 보안 정책 개선

deeptruth/build.gradle, deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java
> ALB 대상 그룹의 헬스체크를 위한 Spring Boot Actuator를 설정하여 서비스 안정성을 개선하였습니다.
- build.gradle에 Spring Boot Actuator 의존성 추가
- application.yml에 헬스체크 엔드포인트 보안 설정
- /actuator/health 경로만 외부 접근 허용하도록 구성
- 기존 Spring Security 설정과 연동하여 보안 강화
> #118 
> 기존 OAuth/JWT 인증 시스템은 그대로 유지되며, 헬스체크만 예외 처리됩니다~
=> Feat: ALB 헬스체크를 위한 Spring Boot Actuator 설정

deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java
> Spring Security에서 CORS 설정을 인식하도록 수정하여 프론트엔드와 백엔드 간 API 통신 시 발생하는 CORS preflight 오류를 해결합니다.
- Spring Security가 WebConfig에 정의된 CORS 설정을 자동으로 적용하도록 연동
- preflight 요청(OPTIONS)이 인증 없이 처리되도록 허용
> #114  #118 
> Spring Security가 CORS를 인식하지 못해 발생한 preflight 리다이렉트 오류를 수정했습니다.
=> Refactor: SecurityConfig에 CORS 설정 연동 추가

deeptruth/src/main/java/com/deeptruth/deeptruth/controller/ProgressController.java
- convertAndSendToUser()를 사용하기위해 전송 경로를 /topic에서 /queue 계열 경로로 변했습니다. 
`convertAndSendToUser()`
- 이 메서드는 Spring의 UserDestinationMessageHandler가 작동해서,
지정한 사용자(Principal 이름)에 연결된 세션에만 메시지를 라우팅합니다. 
| 구독 경로 유형         | 실제 브로커 타입                                       | 메시지 라우팅                          |
| ---------------- | ----------------------------------------------- | -------------------------------- |
| `/topic/**`      | Simple Broker의 “topic” 교환                       | 모든 구독자에게 복제 전송                   |
| `/queue/**`      | Simple Broker의 “queue” 교환                       | 특정 user session 에만 전송            |
| `/user/queue/**` | User Destination Resolver가 로그인 사용자 Principal 매핑 | `convertAndSendToUser()`가 자동 라우팅 |
따라서 ProgressController를 다음과 같이 변경했습니다.
```java
@PostMapping
public …
```
=> Fix: 웹소켓 전송 경로 변경

deeptruth/build.gradle, deeptruth/src/main/java/com/deeptruth/deeptruth/DeeptruthApplication.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/websocket/DeepfakeRequestMessage.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/websocket/TaskAcceptedDTO.java, deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/websocket/TaskEvent.java, deeptruth/src/main/java/com/deeptruth/deeptruth/config/RabbitConfig.java, deeptruth/src/main/java/com/deeptruth/deeptruth/config/WebSocketConfig.java, deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/AmazonS3Service.java, deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java, deeptruth/src/main/java/com/deeptruth/deeptruth/worker/DeepfakeWorker.java
동기 HTTP 호출로 Flask 추론을 기다리던 구조를 **RabbitMQ 비동기 파이프라인**으로 전환했습니다.
API 서버는 업로드를 **수신만** 하고 즉시 `202 Accepted` + `taskId`를 반환,
워커가 Flask 호출/결과 처리/DB 저장을 수행한 뒤 **WebSocket(/user/queue/...)** 으로 진행률/완료를 사용자별로 푸시합니다.
대용량 파일은 **S3 Key**, 소용량 이미지는 **byte[] 인라인**으로 큐를 통해 전달합니다.
* **메시징**
* `RabbitConfig` 추가: `deeptruth.direct`(DirectExchange), `deepfake.request.q`, DLX/DLQ 구성, TTL(10분).
* Producer: `rabbitTemplate.convertAndSend(EXCHANGE, ROUTING, message)`로 요청 메시지 발행.
* Consumer(워커): `@RabbitListener` 로 메시지 소비 → Flask `/predict` 호출 → 결과 처리.
* **DTO/전송 정책**
* `DeepfakeRequestMessage` 신설
* `byte[] fileBytes`(작은 이미지 ≤10MB) **또는** `String s3Key`(대용량/영상)
* `originalFilename`, `contentType`, 옵션 필드(mode, detector 등)
* 멀티파트 전송에서 **InputStreamResource 금지** → `ByteArrayResource + byte[]`로 변경(읽기 재시도 안전)
* …
=> Feat:RabbitMQ 기반 비동기 딥페이크 탐지 파이프라인 도입 (Spring ↔ RabbitMQ ↔ Flask ↔ S3 ↔ WebSocket)
